In [1]:
import pandas as pd
print("done install pandas")
import json

done install pandas

In [2]:
# importing dataframe 
df = pd.read_csv('PortPaint_unclean.csv')
df.head()
df

,collectionsURL,unitCode,dataSource,title,EDANid,guid,recordLink,lastUpdateDate,creditLine,date,...,publisher,topic,indexed_dates,indexed_names,indexed_object_types,indexed_places,indexed_topics,mediaCount,mediaURLs,thumbnail
0,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,George Washington,edanmdm:saam_XX108A,http://n2t.net/ark:/65665/vk7c06aa8a1-8da1-47c...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1803?""}",...,NaN,"{""Topic"": ""Occupation\\political\\president\nP...",[1800s],"['Washington, George', 'Winstanley, William']",[Paintings],[],"[Occupations, Men, Portraits, Political, Presi...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-XX108A_1/full...
1,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of Thayendanegea (Joseph Brant),edanmdm:saam_2024.24,http://n2t.net/ark:/65665/vk73fdea64c-bcb4-4a4...,https://americanart.si.edu/collections/search/...,2025-01-16,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""after 1797""}",...,NaN,"{""Topic"": ""Portrait male""}",[1790s],"['Peale, Charles Willson', Portrait male]",[Paintings],[],"[Men, Portraits]",0,[],NaN
2,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,The Davis Children (Eliza Cheever Davis and Jo...,edanmdm:saam_2019.6.12,http://n2t.net/ark:/65665/vk7db2de5a6-554f-456...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1795""}",...,NaN,"{""Topic"": ""Landscape\nObject\\flower\\lily\nPo...",[1790s],"['Savage, Edward', 'Davis, Eliza Cheever', 'Da...",[Paintings],[],"[Women, Landscapes, Men, Portraits, Flowers, C...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2019.6.12_1/f...
3,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of a Gentleman,edanmdm:saam_2012.21,http://n2t.net/ark:/65665/vk79241bdef-7f0c-441...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1793""}",...,NaN,"{""Topic"": ""Portrait male\\bust""}",[1790s],"['Peale, James']",[Paintings],[],"[Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2012.21_1/ful...
4,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,John Swanwick,edanmdm:saam_2010.16.2,http://n2t.net/ark:/65665/vk73f915b19-cb1a-4db...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""ca. 1800""}",...,NaN,"{""Topic"": ""Object\\written matter\\book\nPortr...","[1800s, 1790s]","['Pratt, Matthew', 'Swanwick, John']",[Paintings],[],"[Books and reading, Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2010.16.2_1/f...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,John Winthrop,edanmdm:npg_NPG.2004.1,http://n2t.net/ark:/65665/sm494570a5b-7dbe-446...,https://npg.si.edu/object/npg_NPG.2004.1,2025-03-13,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""c. 1800, after early 17th century or...",...,NaN,"{""Topic"": ""Costume\\Dress Accessory\\Neckwear\...","[1800s, 1790s]","['Winthrop, John']",[Paintings],[Massachusetts],"[Neckwear, Ruff, Government, Dress accessories...",1,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-NPG_2004_1/ful...
259,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,John Ewing,edanmdm:npg_NPG.2001.5,http://n2t.net/ark:/65665/sm4f1d59b40-d63d-4ec...,https://npg.si.edu/object/npg_NPG.2001.5,2025-03-19,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""1788""}",...,NaN,"{""Topic"": ""Printed Material\\Papers\nHome Furn...",[1780s],"['Ewing, John', 'Peale, Charles Willson']",[Paintings],"[United States, North America, Philadelphia, P...","[Optical Devices, Arts and Culture, Papers, Qu...",1,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-NPG_2001_15/fu...
260,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,Daniel Morgan,edanmdm:npg_NPG.2001.3,http://n2t.net/ark:/65665/sm4a18db5c3-e3ec-403...,https://npg.si.edu/object/npg_NPG.2001.3,2025-03-13,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""c. 1780""}",...,NaN,"{""Topic"": ""Daniel Morgan: Male\nDaniel Morgan:...",[1780s],"[United States. Army, 'Morgan, Daniel']",[Paintings],"[United States, Virginia]","[Legislators, Congressional Gold Medal, Congre...",1,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-NPG_2001_3Morg...
261,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,George Washington (Lansdowne Portrait),edanmdm:npg_NPG.2001.13,http://n2t.net/ark:/65665/sm46a76a395-dbbe-4e5...,https://npg.si.edu/object/npg_NPG.2001.13,2025-06-10,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""1796""}",...,NaN,"{""Topic"": ""Printed Material\\Book\nPrinted Mat...",[1790s],"[United States. Army, 'Washington, George', 'S...",[Paintings],"[Franklin, United States, North America, Germa...","[Business and Finance, Books and reading, Pape...",1,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-NPG_2001_13_ex...
262,https://collections.si.edu/search/detail/edanm...,NMAH,National Museum of American History,George Washington,edanmdm:nmah_214479,https://n2t.net/ark:/65665/ng49ca746a0-ede7-70...,NaN,2025-08-01,NaN,"{""Date made"": ""circa 1793""}",...,NaN,"{""depicted"": ""Presidents"", ""general subject as...",[1790s],"['Washington, George', 'Trumbull, John']","[Paintings, 'Painting, Portrait', Portraits]",[],"[Government, Social reformers, Portraits, Poli...",3,['https://ids.si.edu/ids/deliveryService?id=NM...,https://ids.si.edu/ids/iiif/NMAH-89-6827/full/...

In [3]:
df.iloc[0]
df["name"][0]
print(type(df["name"][0]))
print(df["name"][0])
df.head()

<class 'str'>
{"Attributed to": "William Winstanley, born England, active 1775-1806", "Sitter": "George Washington"}

,collectionsURL,unitCode,dataSource,title,EDANid,guid,recordLink,lastUpdateDate,creditLine,date,...,publisher,topic,indexed_dates,indexed_names,indexed_object_types,indexed_places,indexed_topics,mediaCount,mediaURLs,thumbnail
0,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,George Washington,edanmdm:saam_XX108A,http://n2t.net/ark:/65665/vk7c06aa8a1-8da1-47c...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1803?""}",...,NaN,"{""Topic"": ""Occupation\\political\\president\nP...",[1800s],"['Washington, George', 'Winstanley, William']",[Paintings],[],"[Occupations, Men, Portraits, Political, Presi...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-XX108A_1/full...
1,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of Thayendanegea (Joseph Brant),edanmdm:saam_2024.24,http://n2t.net/ark:/65665/vk73fdea64c-bcb4-4a4...,https://americanart.si.edu/collections/search/...,2025-01-16,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""after 1797""}",...,NaN,"{""Topic"": ""Portrait male""}",[1790s],"['Peale, Charles Willson', Portrait male]",[Paintings],[],"[Men, Portraits]",0,[],NaN
2,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,The Davis Children (Eliza Cheever Davis and Jo...,edanmdm:saam_2019.6.12,http://n2t.net/ark:/65665/vk7db2de5a6-554f-456...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1795""}",...,NaN,"{""Topic"": ""Landscape\nObject\\flower\\lily\nPo...",[1790s],"['Savage, Edward', 'Davis, Eliza Cheever', 'Da...",[Paintings],[],"[Women, Landscapes, Men, Portraits, Flowers, C...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2019.6.12_1/f...
3,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of a Gentleman,edanmdm:saam_2012.21,http://n2t.net/ark:/65665/vk79241bdef-7f0c-441...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1793""}",...,NaN,"{""Topic"": ""Portrait male\\bust""}",[1790s],"['Peale, James']",[Paintings],[],"[Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2012.21_1/ful...
4,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,John Swanwick,edanmdm:saam_2010.16.2,http://n2t.net/ark:/65665/vk73f915b19-cb1a-4db...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""ca. 1800""}",...,NaN,"{""Topic"": ""Object\\written matter\\book\nPortr...","[1800s, 1790s]","['Pratt, Matthew', 'Swanwick, John']",[Paintings],[],"[Books and reading, Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2010.16.2_1/f...

In [5]:
#Extract from ["name"] column and add to new "Sitter" Column
df["Sitter"] = df["name"].str.extract(r'"Sitter"\s*:\s*"([^"]*)"')
#add artist column
df["Artist"] = df["name"].str.extract(
    r'"Artist"\s*:\s*"([^"]*)"|'
    r'"Attributed to"\s*:\s*"([^"]*)"|'
    r'"Attribution"\s*:\s*"([^"]*)"|'
    r'"Engraver"\s*:\s*"([^"]*)"'
).bfill(axis=1).iloc[:, 0]
#extract date from date column
df["Clean_Date"] = df["date"].str.extract(r'"Date"\s*:\s*"([^"]*)"')

import re
# extract gender from indexecd_topics
df["Gender"] = df["indexed_topics"].str.extract(r'(Men|Women)', flags=re.IGNORECASE)
print("done")
df.head()

done

/var/folders/s6/l4_0rpsd3xs3vxs6x047x7t80000gn/T/ipykernel_44716/3652080203.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ).bfill(axis=1).iloc[:, 0]

,collectionsURL,unitCode,dataSource,title,EDANid,guid,recordLink,lastUpdateDate,creditLine,date,...,indexed_object_types,indexed_places,indexed_topics,mediaCount,mediaURLs,thumbnail,Sitter,Artist,Clean_Date,Gender
0,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,George Washington,edanmdm:saam_XX108A,http://n2t.net/ark:/65665/vk7c06aa8a1-8da1-47c...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1803?""}",...,[Paintings],[],"[Occupations, Men, Portraits, Political, Presi...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-XX108A_1/full...,George Washington,"William Winstanley, born England, active 1775-...",1803?,Men
1,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of Thayendanegea (Joseph Brant),edanmdm:saam_2024.24,http://n2t.net/ark:/65665/vk73fdea64c-bcb4-4a4...,https://americanart.si.edu/collections/search/...,2025-01-16,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""after 1797""}",...,[Paintings],[],"[Men, Portraits]",0,[],NaN,Portrait male,Unidentified,after 1797,Men
2,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,The Davis Children (Eliza Cheever Davis and Jo...,edanmdm:saam_2019.6.12,http://n2t.net/ark:/65665/vk7db2de5a6-554f-456...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1795""}",...,[Paintings],[],"[Women, Landscapes, Men, Portraits, Flowers, C...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2019.6.12_1/f...,Eliza Cheever Davis\nJohn Derby Davis,"Edward Savage, born Princeton, MA 1761-died Pr...",1795,Women
3,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of a Gentleman,edanmdm:saam_2012.21,http://n2t.net/ark:/65665/vk79241bdef-7f0c-441...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1793""}",...,[Paintings],[],"[Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2012.21_1/ful...,unidentified,"James Peale, born Chestertown, MD 1749-died Ph...",1793,Men
4,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,John Swanwick,edanmdm:saam_2010.16.2,http://n2t.net/ark:/65665/vk73f915b19-cb1a-4db...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""ca. 1800""}",...,[Paintings],[],"[Books and reading, Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2010.16.2_1/f...,John Swanwick,"Matthew Pratt, born Philadelphia, PA 1734-died...",ca. 1800,Men

In [21]:
#extract occupations from topic
# if the indexed_topics column has "Occupation" in it, extract the list and put it in a new column called "Occupation"
df["Occupation"] = df["indexed_topics"].str.extract(r'(Military|President|Clergy|Medicine|Transportation|Governors|Art |Government)', flags=re.IGNORECASE)
#if Occupation is NaN, fill it with "Civilian"
df["Occupation"] = df["Occupation"].fillna("Civilian")
df.head(20)
df

,collectionsURL,unitCode,dataSource,title,EDANid,guid,recordLink,lastUpdateDate,creditLine,date,...,indexed_places,indexed_topics,mediaCount,mediaURLs,thumbnail,Sitter,Artist,Clean_Date,Gender,Occupation
0,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,George Washington,edanmdm:saam_XX108A,http://n2t.net/ark:/65665/vk7c06aa8a1-8da1-47c...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1803?""}",...,[],"[Occupations, Men, Portraits, Political, Presi...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-XX108A_1/full...,George Washington,William Winstanley,1803,Men,President
1,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of Thayendanegea (Joseph Brant),edanmdm:saam_2024.24,http://n2t.net/ark:/65665/vk73fdea64c-bcb4-4a4...,https://americanart.si.edu/collections/search/...,2025-01-16,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""after 1797""}",...,[],"[Men, Portraits]",0,[],NaN,Portrait male,Unidentified,1797,Men,Civilian
2,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,The Davis Children (Eliza Cheever Davis and Jo...,edanmdm:saam_2019.6.12,http://n2t.net/ark:/65665/vk7db2de5a6-554f-456...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1795""}",...,[],"[Women, Landscapes, Men, Portraits, Flowers, C...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2019.6.12_1/f...,Eliza Cheever Davis\nJohn Derby Davis,Edward Savage,1795,Women,Civilian
3,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of a Gentleman,edanmdm:saam_2012.21,http://n2t.net/ark:/65665/vk79241bdef-7f0c-441...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1793""}",...,[],"[Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2012.21_1/ful...,unidentified,James Peale,1793,Men,Civilian
4,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,John Swanwick,edanmdm:saam_2010.16.2,http://n2t.net/ark:/65665/vk73f915b19-cb1a-4db...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""ca. 1800""}",...,[],"[Books and reading, Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2010.16.2_1/f...,John Swanwick,Matthew Pratt,1800,Men,Civilian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,William Linn,edanmdm:npg_NPG.2007.11,http://n2t.net/ark:/65665/sm44a9659c3-58cb-4ab...,https://npg.si.edu/object/npg_NPG.2007.11,2024-12-03,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""early 1790s""}",...,[],"[Religion and Spirituality, Men, Portraits, Cl...",2,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-NPG_2007_11Lin...,William Linn,Archibald Robertson,1790,Men,Clergy
257,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,John Winthrop,edanmdm:npg_NPG.2004.1,http://n2t.net/ark:/65665/sm494570a5b-7dbe-446...,https://npg.si.edu/object/npg_NPG.2004.1,2025-03-13,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""c. 1800, after early 17th century or...",...,[Massachusetts],"[Neckwear, Ruff, Government, Dress accessories...",1,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-NPG_2004_1/ful...,John Winthrop,Unidentified Artist,1800,men,Government
258,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,John Ewing,edanmdm:npg_NPG.2001.5,http://n2t.net/ark:/65665/sm4f1d59b40-d63d-4ec...,https://npg.si.edu/object/npg_NPG.2001.5,2025-03-19,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""1788""}",...,"[United States, North America, Philadelphia, P...","[Optical Devices, Arts and Culture, Papers, Qu...",1,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-NPG_2001_15/fu...,John Ewing,Charles Willson Peale,1788,men,Clergy
259,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,Daniel Morgan,edanmdm:npg_NPG.2001.3,http://n2t.net/ark:/65665/sm4a18db5c3-e3ec-403...,https://npg.si.edu/object/npg_NPG.2001.3,2025-03-13,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""c. 1780""}",...,"[United States, Virginia]","[Legislators, Congressional Gold Medal, Congre...",1,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-NPG_2001_3Morg...,Daniel Morgan,Unidentified Artist,1780,men,Government
260,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,George Washington (Lansdowne Portrait),edanmdm:npg_NPG.2001.13,http://n2t.net/ark:/65665/sm46a76a395-dbbe-4e5...,https://npg.si.edu/object/npg_NPG.2001.13,2025-06-10,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""1796""}",...,"[Franklin, United States, North America, Germa...","[Business and Finance, Books and reading, Pape...",1,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-NPG_2001_13_ex...,George Washington,Gilbert Stuart,1796,men,Military

In [22]:
#Drop NAs
df = df[df["Sitter"].notna()].reset_index(drop=True)
#remove dates from end of some names
df["Sitter"] = df["Sitter"].str.split(",", n=1).str[0].str.strip()
#remove extraneous info from the end of some artists
df["Artist"] = df["Artist"].str.split(",", n = 1).str[0].str.strip()
#only keep numbers in Clean_Date
df["Clean_Date"] = df["Clean_Date"].astype(str).str.extract('(\d+)').astype(int)

df["Clean_Date"]


# df.to_csv("check_dates.csv")
# df.head()
df.head()

,collectionsURL,unitCode,dataSource,title,EDANid,guid,recordLink,lastUpdateDate,creditLine,date,...,indexed_places,indexed_topics,mediaCount,mediaURLs,thumbnail,Sitter,Artist,Clean_Date,Gender,Occupation
0,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,George Washington,edanmdm:saam_XX108A,http://n2t.net/ark:/65665/vk7c06aa8a1-8da1-47c...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1803?""}",...,[],"[Occupations, Men, Portraits, Political, Presi...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-XX108A_1/full...,George Washington,William Winstanley,1803,Men,President
1,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of Thayendanegea (Joseph Brant),edanmdm:saam_2024.24,http://n2t.net/ark:/65665/vk73fdea64c-bcb4-4a4...,https://americanart.si.edu/collections/search/...,2025-01-16,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""after 1797""}",...,[],"[Men, Portraits]",0,[],NaN,Portrait male,Unidentified,1797,Men,Civilian
2,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,The Davis Children (Eliza Cheever Davis and Jo...,edanmdm:saam_2019.6.12,http://n2t.net/ark:/65665/vk7db2de5a6-554f-456...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1795""}",...,[],"[Women, Landscapes, Men, Portraits, Flowers, C...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2019.6.12_1/f...,Eliza Cheever Davis\nJohn Derby Davis,Edward Savage,1795,Women,Civilian
3,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of a Gentleman,edanmdm:saam_2012.21,http://n2t.net/ark:/65665/vk79241bdef-7f0c-441...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1793""}",...,[],"[Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2012.21_1/ful...,unidentified,James Peale,1793,Men,Civilian
4,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,John Swanwick,edanmdm:saam_2010.16.2,http://n2t.net/ark:/65665/vk73f915b19-cb1a-4db...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""ca. 1800""}",...,[],"[Books and reading, Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2010.16.2_1/f...,John Swanwick,Matthew Pratt,1800,Men,Civilian

In [23]:
#Export here:
df.to_csv("PortPaint_Clean.csv", index=False)

In [17]:
#summary df
sitter_counts = df["Sitter"].value_counts().reset_index()
sitter_counts.columns = ["Sitter", "Count"]
print(sitter_counts)

NameError: name 'df' is not defined

In [62]:
sitter_counts.to_csv("sitter_counts_test.csv")

Take cleaned.csv and remove sitters not used for project 2

In [18]:
clean_before_removal = pd.read_csv("cleaned.csv")
clean_before_removal.head()

,collectionsURL,unitCode,dataSource,title,EDANid,guid,recordLink,lastUpdateDate,creditLine,date,...,indexed_names,indexed_object_types,indexed_places,indexed_topics,mediaCount,mediaURLs,thumbnail,Sitter,Artist,Clean_Date
0,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,George Washington,edanmdm:saam_XX108A,http://n2t.net/ark:/65665/vk7c06aa8a1-8da1-47c...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1803?""}",...,"['Washington, George', 'Winstanley, William']",[Paintings],[],"[Occupations, Men, Portraits, Political, Presi...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-XX108A_1/full...,George Washington,William Winstanley,1803
1,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of Thayendanegea (Joseph Brant),edanmdm:saam_2024.24,http://n2t.net/ark:/65665/vk73fdea64c-bcb4-4a4...,https://americanart.si.edu/collections/search/...,2025-01-16,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""after 1797""}",...,"['Peale, Charles Willson', Portrait male]",[Paintings],[],"[Men, Portraits]",0,[],NaN,Portrait male,Unidentified,1797
2,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,The Davis Children (Eliza Cheever Davis and Jo...,edanmdm:saam_2019.6.12,http://n2t.net/ark:/65665/vk7db2de5a6-554f-456...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1795""}",...,"['Savage, Edward', 'Davis, Eliza Cheever', 'Da...",[Paintings],[],"[Women, Landscapes, Men, Portraits, Flowers, C...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2019.6.12_1/f...,Eliza Cheever Davis\nJohn Derby Davis,Edward Savage,1795
3,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of a Gentleman,edanmdm:saam_2012.21,http://n2t.net/ark:/65665/vk79241bdef-7f0c-441...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1793""}",...,"['Peale, James']",[Paintings],[],"[Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2012.21_1/ful...,unidentified,James Peale,1793
4,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,John Swanwick,edanmdm:saam_2010.16.2,http://n2t.net/ark:/65665/vk73f915b19-cb1a-4db...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""ca. 1800""}",...,"['Pratt, Matthew', 'Swanwick, John']",[Paintings],[],"[Books and reading, Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2010.16.2_1/f...,John Swanwick,Matthew Pratt,1800

In [19]:
sitters_to_keep = ["George Washington",
    "Benjamin Franklin",
    "Thomas Jefferson",
    "John Adams",
    "Alexander Hamilton",
    "James Madison"
]
cleaned_test = clean_before_removal[clean_before_removal["Sitter"].isin(sitters_to_keep)].reset_index(drop=True)

In [20]:
print(cleaned_test["Sitter"].value_counts())
cleaned_test

Sitter
George Washington     84
Benjamin Franklin     26
Thomas Jefferson      23
John Adams            10
Alexander Hamilton     8
James Madison          6
Name: count, dtype: int64

,collectionsURL,unitCode,dataSource,title,EDANid,guid,recordLink,lastUpdateDate,creditLine,date,...,indexed_names,indexed_object_types,indexed_places,indexed_topics,mediaCount,mediaURLs,thumbnail,Sitter,Artist,Clean_Date
0,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,George Washington,edanmdm:saam_XX108A,http://n2t.net/ark:/65665/vk7c06aa8a1-8da1-47c...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1803?""}",...,"['Washington, George', 'Winstanley, William']",[Paintings],[],"[Occupations, Men, Portraits, Political, Presi...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-XX108A_1/full...,George Washington,William Winstanley,1803
1,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Mourning Piece for George Washington,edanmdm:saam_1971.111,http://n2t.net/ark:/65665/vk7b2f8e20a-81fb-4f2...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1810""}",...,"['Washington, George', 'Gridley, Enoch G.']",[Graphic arts],[Washington],"[Soldiers, Memorials, Occupations, Men, Monume...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-1971.111_1/fu...,George Washington,Enoch G. Gridley,1810
2,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,George Washington,edanmdm:saam_1971.102,http://n2t.net/ark:/65665/vk74652dc00-4f71-488...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""ca. 1800-1825""}",...,"['Washington, George', 'Fiquet, H.', 'Trumbull...",[Graphic arts],[],"[Uniforms, Landscapes, Animals, Occupations, C...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-1971.102_1/fu...,George Washington,NaN,1800
3,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,Benjamin Franklin,edanmdm:npg_S_NPG.87.222,http://n2t.net/ark:/65665/sm4c77a42c7-3a26-4b6...,https://npg.si.edu/object/npg_S_NPG.87.222,2025-03-19,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""1782""}",...,"['Franklin, Benjamin', 'Pelicier, J.']","[Maps, Prints]",[],"[Social Welfare and Reform, Business and Finan...",1,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-S_NPG_87_222/f...,Benjamin Franklin,J. Pelicier,1782
4,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,George Washington,edanmdm:npg_S_NPG.85.297,http://n2t.net/ark:/65665/sm4b8e95381-ee00-454...,https://npg.si.edu/object/npg_S_NPG.85.297,2025-05-17,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""1796""}",...,"['Du Simitiere, Pierre Eugene', United States....",[Prints],[United States],"[Business and Finance, Congressional Gold Meda...",1,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-S-NPG_85_297/f...,George Washington,Louis Charles Ruotte,1796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,Alexander Hamilton,edanmdm:npg_NPG.2003.72,http://n2t.net/ark:/65665/sm4e9c8bb92-5e05-4d8...,https://npg.si.edu/object/npg_NPG.2003.72,2025-03-20,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""c. 1800-04""}",...,"['Graham, George', United States. Army, 'Hamil...",[Prints],[],"[Legislators, Books and reading, Arts and Cult...",1,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-NPG_2003_72Ham...,Alexander Hamilton,George Graham,1800
153,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,George Washington,edanmdm:npg_NPG.2002.384,http://n2t.net/ark:/65665/sm4c1771bc3-446a-466...,https://npg.si.edu/object/npg_NPG.2002.384,2025-03-19,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""1798""}",...,"[United States. Army, 'Washington, George', 'E...",[Prints],[United States],"[Office, Business and Finance, Natural resourc...",1,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-NPG_2002_384/f...,George Washington,David Edwin,1798
154,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,Thomas Jefferson,edanmdm:npg_NPG.2002.184.62,http://n2t.net/ark:/65665/sm4675cd41c-80fe-4a7...,https://npg.si.edu/object/npg_NPG.2002.184.62,2025-03-19,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""c. 1803-04""}",...,"['Jefferson, Thomas', 'Bache, William']",[Silhouettes],"[United States, Virginia]","[Business and Finance, Legislators, Cut-out, A...",1,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-NPG_2002_184_6...,Thomas Jefferson,William Bache,1803
155,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,George Washington,edanmdm:npg_NPG.2002.184.5,http://n2t.net/ark:/65665/sm414b2a532-95ef-4a6...,https://npg.si.edu/object/npg_NPG.2002.184.5,2025-03-19,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""c. 1803-04""}",...,"[United States. Army, 'Washington, George', 'B...",[Silhouettes],[United States],"[Business and Finance, Congressional Gold Meda...",1,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-NPG_2002_184_5...,George Washington,William Bache,1803
156,https://collections.si.edu/search/detail/edanm...,NPG,National Portrait Gallery,George Washington (Lansdowne Portrait),edanmdm:npg_NPG.2001.13,http://n2t.net/ark:/65665/sm46a76a395-dbbe-4e5...,https://npg.si.edu/object/npg_NPG.2001.13,2025-06-10,"{""Credit Line"": ""National Portrait Gallery, Sm...","{""Date"": ""1796""}",...,"[United States. Army, 'Washington, George', 'S...",[Paintings],"[Franklin, United States, North America, Germa...","[Business and Finance, Books and reading, Pape...",1,['https://ids.si.edu/ids/deliveryService?id=NP...,https://ids.si.edu/ids/iiif/NPG-NPG_2001_13_ex...,George Washington,Gilbert Stuart,1796

In [25]:
cleaned_test.to_csv("cleaned_test.csv")

In [28]:
#testing if pandas can read the data
readable = pd.read_csv("cleaned_test.csv")
readable_from_github = pd.read_csv("https://raw.githubusercontent.com/nmolnar-parsons/major-studio-1/refs/heads/main/Project_2/Data/cleaned_test.csv")