In [1]:
import pandas as pd
print("done install pandas")
import json

done install pandas

In [12]:
# importing dataframe 
df = pd.read_csv('all_types_unclean.csv')
df.head()
df

,collectionsURL,unitCode,dataSource,title,EDANid,guid,recordLink,lastUpdateDate,creditLine,date,...,publisher,topic,indexed_dates,indexed_names,indexed_object_types,indexed_places,indexed_topics,mediaCount,mediaURLs,thumbnail
0,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,George Washington,edanmdm:saam_XX108A,http://n2t.net/ark:/65665/vk7c06aa8a1-8da1-47c...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1803?""}",...,NaN,"{""Topic"": ""Occupation\\political\\president\nP...",[1800s],"['Washington, George', 'Winstanley, William']",[Paintings],[],"[Occupations, Men, Portraits, Political, Presi...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-XX108A_1/full...
1,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of Thayendanegea (Joseph Brant),edanmdm:saam_2024.24,http://n2t.net/ark:/65665/vk73fdea64c-bcb4-4a4...,https://americanart.si.edu/collections/search/...,2025-01-16,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""after 1797""}",...,NaN,"{""Topic"": ""Portrait male""}",[1790s],"['Peale, Charles Willson', Portrait male]",[Paintings],[],"[Men, Portraits]",0,[],NaN
2,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,The Davis Children (Eliza Cheever Davis and Jo...,edanmdm:saam_2019.6.12,http://n2t.net/ark:/65665/vk7db2de5a6-554f-456...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1795""}",...,NaN,"{""Topic"": ""Landscape\nObject\\flower\\lily\nPo...",[1790s],"['Savage, Edward', 'Davis, Eliza Cheever', 'Da...",[Paintings],[],"[Women, Landscapes, Men, Portraits, Flowers, C...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2019.6.12_1/f...
3,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of a Gentleman,edanmdm:saam_2012.21,http://n2t.net/ark:/65665/vk79241bdef-7f0c-441...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1793""}",...,NaN,"{""Topic"": ""Portrait male\\bust""}",[1790s],"['Peale, James']",[Paintings],[],"[Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2012.21_1/ful...
4,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,John Swanwick,edanmdm:saam_2010.16.2,http://n2t.net/ark:/65665/vk73f915b19-cb1a-4db...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""ca. 1800""}",...,NaN,"{""Topic"": ""Object\\written matter\\book\nPortr...","[1800s, 1790s]","['Pratt, Matthew', 'Swanwick, John']",[Paintings],[],"[Books and reading, Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2010.16.2_1/f...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3322,https://collections.si.edu/search/detail/edanm...,NMAH,National Museum of American History,William Wissing,edanmdm:nmah_1002735,https://n2t.net/ark:/65665/ng49ca746a8-8fdf-70...,NaN,2024-10-16,NaN,"{""date made"": ""18th century""}",...,NaN,"{""Subject"": ""Portraits""}",[1800s],"['Walker, Anthony']","['Engravings (prints)', Prints]","[England, London, United Kingdom]","[Art, Portraits]",0,[],NaN
3323,https://collections.si.edu/search/detail/edanm...,NMAH,National Museum of American History,Guillaume Du Vair,edanmdm:nmah_1002731,https://n2t.net/ark:/65665/ng49ca746ad-c883-70...,NaN,2024-11-22,NaN,"{""date made"": ""18th century""}",...,NaN,"{""Subject"": ""Portraits""}",[1800s],"['Lamsvelt, Jan']","['Engravings (prints)', Prints]",[],"[Art, Portraits]",0,[],NaN
3324,https://collections.si.edu/search/detail/edanm...,NMAH,National Museum of American History,Portrait of a Boy,edanmdm:nmah_1002729,https://n2t.net/ark:/65665/ng49ca746a8-8ecd-70...,NaN,2024-10-16,NaN,"{""Date made"": ""1778""}",...,NaN,"{""Subject"": ""Portraits""}",[1770s],"['Netscher, Caspar', Basan & Poignant, 'Hemery...","['Engravings (prints)', Prints]",[],"[Art, Portraits]",0,[],NaN
3325,https://collections.si.edu/search/detail/edanm...,NMAH,National Museum of American History,Christian Weise,edanmdm:nmah_1002727,https://n2t.net/ark:/65665/ng49ca746a8-8ec7-70...,NaN,2024-11-22,NaN,"{""date made"": ""18th century""}",...,NaN,"{""Subject"": ""Portraits""}",[1800s],"['Bernigeroth, Martin']","['Engravings (prints)', Prints]",[],"[Art, Portraits]",0,[],NaN
3326,https://collections.si.edu/search/detail/edanm...,NMAH,National Museum of American History,Mona Lisa,edanmdm:nmah_1002720,https://n2t.net/ark:/65665/ng49ca746ad-de0e-70...,NaN,2024-11-22,NaN,"{""date made"": ""ca 1803-1809""}",...,NaN,"{""Subject"": ""Portraits""}",[1800s],"['Bouillon, Pierre', 'da Vinci, Leonardo', 'Ma...","['Engravings (prints)', Prints]","[Île-de-France, France, Paris]","[Art, Portraits]",0,[],NaN

In [13]:
df.iloc[0]
df["name"][0]
print(type(df["name"][0]))
print(df["name"][0])
df.head()

<class 'str'>
{"Attributed to": "William Winstanley, born England, active 1775-1806", "Sitter": "George Washington"}

,collectionsURL,unitCode,dataSource,title,EDANid,guid,recordLink,lastUpdateDate,creditLine,date,...,publisher,topic,indexed_dates,indexed_names,indexed_object_types,indexed_places,indexed_topics,mediaCount,mediaURLs,thumbnail
0,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,George Washington,edanmdm:saam_XX108A,http://n2t.net/ark:/65665/vk7c06aa8a1-8da1-47c...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1803?""}",...,NaN,"{""Topic"": ""Occupation\\political\\president\nP...",[1800s],"['Washington, George', 'Winstanley, William']",[Paintings],[],"[Occupations, Men, Portraits, Political, Presi...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-XX108A_1/full...
1,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of Thayendanegea (Joseph Brant),edanmdm:saam_2024.24,http://n2t.net/ark:/65665/vk73fdea64c-bcb4-4a4...,https://americanart.si.edu/collections/search/...,2025-01-16,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""after 1797""}",...,NaN,"{""Topic"": ""Portrait male""}",[1790s],"['Peale, Charles Willson', Portrait male]",[Paintings],[],"[Men, Portraits]",0,[],NaN
2,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,The Davis Children (Eliza Cheever Davis and Jo...,edanmdm:saam_2019.6.12,http://n2t.net/ark:/65665/vk7db2de5a6-554f-456...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1795""}",...,NaN,"{""Topic"": ""Landscape\nObject\\flower\\lily\nPo...",[1790s],"['Savage, Edward', 'Davis, Eliza Cheever', 'Da...",[Paintings],[],"[Women, Landscapes, Men, Portraits, Flowers, C...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2019.6.12_1/f...
3,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of a Gentleman,edanmdm:saam_2012.21,http://n2t.net/ark:/65665/vk79241bdef-7f0c-441...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1793""}",...,NaN,"{""Topic"": ""Portrait male\\bust""}",[1790s],"['Peale, James']",[Paintings],[],"[Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2012.21_1/ful...
4,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,John Swanwick,edanmdm:saam_2010.16.2,http://n2t.net/ark:/65665/vk73f915b19-cb1a-4db...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""ca. 1800""}",...,NaN,"{""Topic"": ""Object\\written matter\\book\nPortr...","[1800s, 1790s]","['Pratt, Matthew', 'Swanwick, John']",[Paintings],[],"[Books and reading, Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2010.16.2_1/f...

In [14]:
#Extract from ["name"] column and add to new "Sitter" Column
df["Sitter"] = df["name"].str.extract(r'"Sitter"\s*:\s*"([^"]*)"')
#add artist column
df["Artist"] = df["name"].str.extract(
    r'"Artist"\s*:\s*"([^"]*)"|'
    r'"Attributed to"\s*:\s*"([^"]*)"|'
    r'"Attribution"\s*:\s*"([^"]*)"|'
    r'"Engraver"\s*:\s*"([^"]*)"'
).bfill(axis=1).iloc[:, 0]
#extract date from date column
df["Clean_Date"] = df["date"].str.extract(r'"Date"\s*:\s*"([^"]*)"')

import re
#extract gender from indexecd_topics
# df["Gender"] = df["indexed_topics"].str.extract(r'(Men|Women)', flags=re.IGNORECASE)
#extract occupations from topic
#df["Occupation"] = df["indexed_topics"].str.extract(r'(Scientists|Artists|Writers|Politicians|Philosophers|Religious Figures|Businesspeople|Athletes|Musicians|Actors|Military Figures)', flags=re.IGNORECASE)

print("done")
df.head()

done

,collectionsURL,unitCode,dataSource,title,EDANid,guid,recordLink,lastUpdateDate,creditLine,date,...,indexed_names,indexed_object_types,indexed_places,indexed_topics,mediaCount,mediaURLs,thumbnail,Sitter,Artist,Clean_Date
0,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,George Washington,edanmdm:saam_XX108A,http://n2t.net/ark:/65665/vk7c06aa8a1-8da1-47c...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1803?""}",...,"['Washington, George', 'Winstanley, William']",[Paintings],[],"[Occupations, Men, Portraits, Political, Presi...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-XX108A_1/full...,George Washington,"William Winstanley, born England, active 1775-...",1803?
1,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of Thayendanegea (Joseph Brant),edanmdm:saam_2024.24,http://n2t.net/ark:/65665/vk73fdea64c-bcb4-4a4...,https://americanart.si.edu/collections/search/...,2025-01-16,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""after 1797""}",...,"['Peale, Charles Willson', Portrait male]",[Paintings],[],"[Men, Portraits]",0,[],NaN,Portrait male,Unidentified,after 1797
2,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,The Davis Children (Eliza Cheever Davis and Jo...,edanmdm:saam_2019.6.12,http://n2t.net/ark:/65665/vk7db2de5a6-554f-456...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1795""}",...,"['Savage, Edward', 'Davis, Eliza Cheever', 'Da...",[Paintings],[],"[Women, Landscapes, Men, Portraits, Flowers, C...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2019.6.12_1/f...,Eliza Cheever Davis\nJohn Derby Davis,"Edward Savage, born Princeton, MA 1761-died Pr...",1795
3,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of a Gentleman,edanmdm:saam_2012.21,http://n2t.net/ark:/65665/vk79241bdef-7f0c-441...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1793""}",...,"['Peale, James']",[Paintings],[],"[Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2012.21_1/ful...,unidentified,"James Peale, born Chestertown, MD 1749-died Ph...",1793
4,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,John Swanwick,edanmdm:saam_2010.16.2,http://n2t.net/ark:/65665/vk73f915b19-cb1a-4db...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""ca. 1800""}",...,"['Pratt, Matthew', 'Swanwick, John']",[Paintings],[],"[Books and reading, Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2010.16.2_1/f...,John Swanwick,"Matthew Pratt, born Philadelphia, PA 1734-died...",ca. 1800

In [15]:
#Drop NAs
df = df[df["Sitter"].notna()].reset_index(drop=True)
#remove dates from end of some names
df["Sitter"] = df["Sitter"].str.split(",", n=1).str[0].str.strip()
#remove extraneous info from the end of some artists
df["Artist"] = df["Artist"].str.split(",", n = 1).str[0].str.strip()
#only keep numbers in Clean_Date
df["Clean_Date"] = df["Clean_Date"].astype(str).str.extract('(\d+)').astype(int)

df["Clean_Date"]


# df.to_csv("check_dates.csv")
# df.head()
df.head()

,collectionsURL,unitCode,dataSource,title,EDANid,guid,recordLink,lastUpdateDate,creditLine,date,...,indexed_names,indexed_object_types,indexed_places,indexed_topics,mediaCount,mediaURLs,thumbnail,Sitter,Artist,Clean_Date
0,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,George Washington,edanmdm:saam_XX108A,http://n2t.net/ark:/65665/vk7c06aa8a1-8da1-47c...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1803?""}",...,"['Washington, George', 'Winstanley, William']",[Paintings],[],"[Occupations, Men, Portraits, Political, Presi...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-XX108A_1/full...,George Washington,William Winstanley,1803
1,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of Thayendanegea (Joseph Brant),edanmdm:saam_2024.24,http://n2t.net/ark:/65665/vk73fdea64c-bcb4-4a4...,https://americanart.si.edu/collections/search/...,2025-01-16,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""after 1797""}",...,"['Peale, Charles Willson', Portrait male]",[Paintings],[],"[Men, Portraits]",0,[],NaN,Portrait male,Unidentified,1797
2,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,The Davis Children (Eliza Cheever Davis and Jo...,edanmdm:saam_2019.6.12,http://n2t.net/ark:/65665/vk7db2de5a6-554f-456...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1795""}",...,"['Savage, Edward', 'Davis, Eliza Cheever', 'Da...",[Paintings],[],"[Women, Landscapes, Men, Portraits, Flowers, C...",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2019.6.12_1/f...,Eliza Cheever Davis\nJohn Derby Davis,Edward Savage,1795
3,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,Portrait of a Gentleman,edanmdm:saam_2012.21,http://n2t.net/ark:/65665/vk79241bdef-7f0c-441...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""1793""}",...,"['Peale, James']",[Paintings],[],"[Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2012.21_1/ful...,unidentified,James Peale,1793
4,https://collections.si.edu/search/detail/edanm...,SAAM,Smithsonian American Art Museum,John Swanwick,edanmdm:saam_2010.16.2,http://n2t.net/ark:/65665/vk73f915b19-cb1a-4db...,https://americanart.si.edu/collections/search/...,2024-11-22,"{""Credit Line"": ""Smithsonian American Art Muse...","{""Date"": ""ca. 1800""}",...,"['Pratt, Matthew', 'Swanwick, John']",[Paintings],[],"[Books and reading, Men, Portraits]",1,['https://ids.si.edu/ids/deliveryService?id=SA...,https://ids.si.edu/ids/iiif/SAAM-2010.16.2_1/f...,John Swanwick,Matthew Pratt,1800

In [16]:
#Export here:
df.to_csv("cleaned.csv", index=False)

In [11]:
#summary df
sitter_counts = df["Sitter"].value_counts().reset_index()
sitter_counts.columns = ["Sitter", "Count"]
print(sitter_counts)

                      Sitter  Count
0           Unidentified Man    658
1         Unidentified Woman    391
2          George Washington     84
3           Unidentified Boy     46
4               unidentified     42
...                      ...    ...
1670              de Messimy      1
1671             Boss\u00e9e      1
1672    Benjamin Ives Gilman      1
1673  David Montague Erskine      1
1674           Daniel Morgan      1

[1675 rows x 2 columns]

In [62]:
sitter_counts.to_csv("sitter_counts_test.csv")